name: Branch Build

on:
  push:
    branches:
      - '**'
      - '!main'

env:
  PROJECT_NAME: CloudCrusher
  PROJECT_VERSION: 1.0.1
  VST3_DIR: ./build/CloudCrusher_artefacts/Release/VST3

jobs:
  upload-artifact:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: "(JUCE) Clone Repository"
        uses: actions/checkout@v3
        with:
          repository: juce-framework/JUCE
          path: ${{ runner.workspace }}/${{ env.PROJECT_NAME }}/JUCE

      - name: Install Xcode Command Line Tools
        run: xcode-select --install || true

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.24'

      - name: Configure project
        run: cmake -B build -S . -G Xcode -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: cmake --build ./build --config Release

      - name: Run unit tests
        run: ctest --test-dir build -C Release -V

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT_NAME }}-${{env.PROJECT_VERSION}}-${{ github.ref_name }}
          path: ${{ env.VST3_DIR }}
          retention-days: 7
