name: Release Build

on:
  push:
    branches:
      - main

env:
  PROJECT_NAME: DelayCrusher
  PROJECT_VERSION: 1.2.0
  VST3_DIR: ./build/DelayCrusher_artefacts/Release/VST3

jobs:
  release-matrix:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: "(JUCE) Clone Repository"
        uses: actions/checkout@v3
        with:
          repository: juce-framework/JUCE
          path: ${{ runner.workspace }}/${{ env.PROJECT_NAME }}/JUCE

      - name: Install Xcode Command Line Tools (macOS only)
        if: matrix.os == 'macos-latest'
        run: xcode-select --install || true

      - name: Install Windows C++ Build Tools (Windows only)
        if: matrix.os == 'windows-latest'
        run: |
          choco install visualstudio2022buildtools --yes --ignore-checksums
          choco install cmake --yes --ignore-checksums
          choco install ninja --yes --ignore-checksums

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.24'

      - name: Configure project (macOS)
        if: matrix.os == 'macos-latest'
        run: cmake -B build -S . -G Xcode -DCMAKE_BUILD_TYPE=Release

      - name: Configure project (Windows)
        if: matrix.os == 'windows-latest'
        run: cmake -B build -S . -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: cmake --build ./build --config Release

      - name: Run unit tests
        run: ctest --test-dir build -C Release -V

      - name: Package release (macOS only)
        if: matrix.os == 'macos-latest'
        run: |
          cd ${{ env.VST3_DIR }}
          zip -r ./${{ env.PROJECT_NAME }}-v${{ env.PROJECT_VERSION }}.zip ${{ env.PROJECT_NAME }}.vst3
          mv ${{ env.PROJECT_NAME }}-v${{ env.PROJECT_VERSION }}.zip ${{ github.workspace }}
          cd ${{ github.workspace }}

      - name: Create GitHub release (macOS only)
        if: matrix.os == 'macos-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        run: >-
          gh release create v${{ env.PROJECT_VERSION }}
          "${{ env.PROJECT_NAME }}-v${{ env.PROJECT_VERSION }}.zip"
          --generate-notes
          --title "Delay Crusher v${{ env.PROJECT_VERSION }}"
