name: Release Build

on:
  push:
    branches:
      - main

env:
  PROJECT_NAME: CloudCrusher
  PROJECT_VERSION: 1.0.0
  VST3_DIR: ./build/CloudCrusher_artefacts/Release/VST3

jobs:
  create-release:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: "(JUCE) Clone Repository"
        uses: actions/checkout@v3
        with:
          repository: juce-framework/JUCE
          path: ${{ runner.workspace }}/${{ env.PROJECT_NAME }}/JUCE

      - name: Install Xcode Command Line Tools
        run: xcode-select --install || true

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.24'

      - name: Configure project
        run: cmake -B build -S . -G Xcode -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: cmake --build ./build --config Release

      - name: Run unit tests
        run: ctest --test-dir build -C Release -V

      - name: Package release
        run: |
          cd ${{ env.VST3_DIR }}
          zip -r ./${{ env.PROJECT_NAME }}-v${{ env.PROJECT_VERSION }}.zip ${{ env.PROJECT_NAME }}.vst3
          mv ${{ env.PROJECT_NAME }}-v${{ env.PROJECT_VERSION }}.zip ${{ github.workspace }}
          cd ${{ github.workspace }}

      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        run: >-
          gh release create v${{ env.PROJECT_VERSION }}
          "${{ env.PROJECT_NAME }}-v${{ env.PROJECT_VERSION }}.zip"
          --generate-notes
          --title "Cloud Crusher v${{ env.PROJECT_VERSION }}"
